version: "3.7"

services:
  wedding_invitation:
    image: shakhboz77/invitation:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/app/node_modules
      - next_cache:/app/.next

volumes:
  node_modules:
  next_cache:
