name: Build and Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for production
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/invitation:latest
            ${{ secrets.DOCKER_USERNAME }}/invitation:${{ github.run_id }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Deploy to Production Server
  #       uses: appleboy/ssh-action@v0.1.3
  #       with:
  #         host: ${{ secrets.PROD_SERVER }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         env:
  #           DOCKER_IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/myapp:latest-production
  #         script: |
  #           docker pull $DOCKER_IMAGE_TAG
  #           docker service update --image $DOCKER_IMAGE_TAG myapp_service_production
