name: Build and Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-bekzod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for production
        uses: docker/build-push-action@v6
        env:
          DEBUG: true
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/invitation:latest
            ${{ secrets.DOCKER_USERNAME }}/invitation:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-bekzod
    needs: build

    steps:
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/invitation:${{ github.run_number }}
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/invitation:${{ github.run_number }} invitation_wedding_invitation
